name: Build LaTeX document
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: type-systems.tex
      - name: Rename file
        id: rename_file
        run: |
          sha_short=$(git rev-parse --short HEAD)
          datetime_now=$(date +'%Y-%m-%dT%H:%M:%S')
          filename=type-systems-$datetime_now-$sha_short.pdf
          echo "filename=$filename" >> $GITHUB_OUTPUT
          echo "sha_short=$sha_short" >> $GITHUB_OUTPUT
          mv type-systems.pdf $filename
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.rename_file.outputs.filename }}
          tag_name: ${{ steps.rename_file.outputs.sha_short }}
          draft: false
          prerelease: false
          files: ${{ steps.rename_file.outputs.filename }}
